# Generated by Django 2.2.4 on 2020-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Introduce el nombre del usuario', max_length=20)),
                ('rank', models.CharField(choices=[('GM', 'Guild Master'), ('O', 'Oficial'), ('R', 'Raider'), ('M', 'Miembro'), ('I', 'Iniciado')], default='I', max_length=2)),
            ],
        ),
    ]
