# Generated by Django 2.2.4 on 2020-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('GM', 'Guild Master'), ('O', 'Oficial'), ('R', 'Raider'), ('M', 'Miembro'), ('I', 'Iniciado')], default='I', max_length=1),
        ),
    ]
