# Generated by Django 2.2.4 on 2020-05-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200528_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('GM', 'Guild Master'), ('O', 'Oficial'), ('R', 'Raider'), ('M', 'Miembro'), ('I', 'Iniciado')], default='I', help_text='Rango del usuario', max_length=1),
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Introduce el nombre del personaje', max_length=20)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Characters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Characters'),
        ),
    ]
