# Generated by Django 2.2.4 on 2020-05-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200528_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Characters',
        ),
    ]
