# Generated by Django 2.2.4 on 2020-05-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200528_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_class', models.CharField(choices=[('Guerrero', 'Guerrero'), ('Paladin', 'Paladin'), ('Cazador', 'Cazador'), ('Picaro', 'Picaro'), ('Sacerdote', 'Sacerdote'), ('Chaman', 'Chaman'), ('Mago', 'Mago'), ('Brujo', 'Brujo'), ('Monje', 'Monje'), ('Druida', 'Druida'), ('Cazador de demonios', 'Cazador de demonios'), ('Caballero de la muerte', 'Caballero de la muerte')], default='DPS', help_text='Seleccion de clase', max_length=1)),
                ('p_rol', models.CharField(choices=[('DPS', 'DPS'), ('TANK', 'TANK'), ('HEAL', 'HEAL')], default='DPS', help_text='Especialización de clase', max_length=1)),
            ],
        ),
    ]
