# Generated by Django 2.2.4 on 2020-05-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_clas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clas',
            old_name='p_class',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='clas',
            old_name='p_rol',
            new_name='Rol',
        ),
    ]
