# Generated by Django 2.2.4 on 2020-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_clas_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Class',
            field=models.CharField(choices=[('Guerrero', 'Guerrero'), ('Paladin', 'Paladin'), ('Cazador', 'Cazador'), ('Picaro', 'Picaro'), ('Sacerdote', 'Sacerdote'), ('Chaman', 'Chaman'), ('Mago', 'Mago'), ('Brujo', 'Brujo'), ('Monje', 'Monje'), ('Druida', 'Druida'), ('Cazador de demonios', 'Cazador de demonios'), ('Caballero de la muerte', 'Caballero de la muerte')], default='DPS', help_text='Seleccion de clase', max_length=1),
        ),
        migrations.AddField(
            model_name='character',
            name='Rol',
            field=models.CharField(choices=[('DPS', 'DPS'), ('TANK', 'TANK'), ('HEAL', 'HEAL')], default='DPS', help_text='Especialización de clase', max_length=1),
        ),
        migrations.DeleteModel(
            name='Clas',
        ),
    ]
