# Generated by Django 2.2.4 on 2020-05-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200529_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Playable_spec',
        ),
    ]
