# Generated by Django 2.2.4 on 2020-05-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_character_playable_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.AlterField(
            model_name='character',
            name='Name',
            field=models.CharField(help_text='Introduce el nombre del personaje', max_length=20, primary_key=True, serialize=False),
        ),
    ]
