# Generated by Django 2.2.4 on 2020-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200529_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Playable_class',
            field=models.CharField(blank=True, choices=[(1, 'Guerrero'), (2, 'Paladin'), (3, 'Cazador'), (4, 'Picaro'), (5, 'Sacerdote'), (6, 'Chaman'), (7, 'Mago'), (8, 'Brujo'), (9, 'Monje'), (10, 'Druida'), (11, 'Cazador de demonios'), (12, 'Caballero de la muerte')], help_text='Introduce la clase del personaje', max_length=2),
        ),
    ]
