# Generated by Django 2.2.4 on 2020-05-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200529_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Playable_class',
            field=models.CharField(blank=True, choices=[('1', 'Guerrero'), ('2', 'Paladin'), ('3', 'Cazador'), ('4', 'Picaro'), ('5', 'Sacerdote'), ('7', 'Chaman'), ('8', 'Mago'), ('9', 'Brujo'), ('10', 'Monje'), ('11', 'Druida'), ('12', 'Cazador de demonios'), ('6', 'Caballero de la muerte')], help_text='Introduce la clase del personaje', max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='Playable_race',
            field=models.CharField(blank=True, choices=[('1', 'Guerrero'), ('2', 'Paladin'), ('3', 'Cazador'), ('4', 'Picaro'), ('5', 'Sacerdote'), ('7', 'Chaman'), ('8', 'Mago'), ('9', 'Brujo'), ('10', 'Monje'), ('11', 'Druida'), ('12', 'Cazador de demonios'), ('6', 'Caballero de la muerte')], help_text='Introduce la raza del personaje', max_length=2),
        ),
    ]
