# Generated by Django 2.2.4 on 2020-05-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200530_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Rank',
            field=models.CharField(choices=[('7', 'Iniciado'), ('6', 'Alter'), ('5', 'Miembro'), ('4', 'Veternao'), ('3', 'Raider'), ('2', 'Alter Oficial'), ('1', 'Oficial'), ('0', 'GM')], default=7, help_text='Introduce el rango del personaje', max_length=1),
        ),
    ]
