# Generated by Django 2.2.4 on 2020-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='Last_update',
            field=models.DateTimeField(),
        ),
    ]
