# Generated by Django 2.2.4 on 2020-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200530_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Avatar_url',
            field=models.CharField(help_text='URL del Avatar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Bust_url',
            field=models.CharField(help_text='URL del Busto', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Render_url',
            field=models.CharField(help_text='URL del Render', max_length=200, null=True),
        ),
    ]
